# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-scrnaseq-1.0.1dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.2
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.8.1
  - bioconda::multiqc=1.10
  - bioconda::salmon=1.4.0
  - bioconda::r-seurat=3.0.2
  - bioconda::bioconductor-isee=2.2.0
  - bioconda::bioconductor-tximeta=1.8.0
  - bioconda::bioawk=1.0
  - bioconda::bioconductor-alevinqc=1.6.0
  - bioconda::bioconductor-tximport=1.18.0
  - bioconda::star=2.7.8a #2.7.3a is broken!
  - samtools=1.12
  - gffread=0.12.1
  - bioconda::kallisto=0.46.2
  - bioconda::bustools=0.40.0
  - font-ttf-source-code-pro=2.030 #Required for fonts in alevinQC
  - pandoc=2.13
  - tbb=2021.1.1 #Fixing a still existing bioconda bug :-) 
